/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<form action="{{getActionUrl}}" id="myForm">\n	<div class="head pic"><img src="{{url}}" id="sh-pic"/></div>\n	<div class="sh-name" id="sh-name">HI,我是{{nickName}}</div>\n	<div class="sh-wd">送你<span>300</span>元优惠劵</div>\n	<div class="sh-wd1">输入手机号即可领取</div>\n	<input type=\'hidden\' class="sh-tel" id="sh-sui" name="sui" value="{{getSui}}"/>\n	<input type=\'tel\' class="sh-tel" placeholder="点此输入手机号" id="sh-tel" name="receiveUser"/>\n	<input type="submit" class="s-button" value="立即领取" id="s-button"/>\n</form>\n';
});