/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<div class="main shop-view">\n	<header class="bar-love header bar">\n		<button class="button button-clear button-back">\n			<i class="icon iconfont icon-back"></i></button>\n		<h1 class="title">{{title}}</h1>\n		<div class="buttons buttons-right" style="-webkit-transition-duration: 0ms; transition-duration: 0ms;">	\n		</div>\n	</header>\n	<div class="content has-header">\n	</div>\n</div>';
});