/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<div class="home">\n	<div id="slider_container" class="slider-container" ></div>\n	<div id="card_container" class="card-container clear-float" ></div>\n</div>';
});