/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<div class="main">\n {{^if isApp}}\n	<header class="bar-love header bar">\n		<a href="javascript:history.go(-1);" class="button button-clear button-back">\n			<i class="icon iconfont icon-back"></i></a>\n		<h1 class="title">河狸家·高颜值</h1>\n		<div class="buttons buttons-right">	\n			<button name="button_search" class="button button-clear icon iconfont icon-search"> </button>\n		</div>\n	</header>\n {{/if}}\n	<div class="content  {{^if isApp}}has-header{{/if}}">\n	</div>\n</div>';
});