/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<div class="tab-body-person">\n <!--  \n	<form action="javascript:;" class="bar bar-header item-input-inset form-search">\n   	<label class="item-input-wrapper">\n   		<i class="icon iconfont placeholder-icon">&#xe611;</i>\n   		<input type="search" placeholder="搜索高颜值手艺人">\n   	</label>\n	</form>\n	 -->\n	<div class="scroll-content artisan-list">\n		{{#each this}}\n		<a href="javascript:;" data-label_code="{{label_code}}" data-type_code="{{type_code}}" class="item item-avatar  item-icon-right" >\n		  <img src="{{getImgAbsolutePath img}}">\n		  <h2>{{title}}</h2>\n		  <p>{{subtitle}}</p>\n		  <i class="icon iconfont icon-forward"></i>\n		</a>\n		{{/each}}\n		\n	</div>\n</div>\n				';
});