/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<div class="scroll-content">\n	<ul class="thing-list clear-float">\n		{{#each this}}\n		<li class="card-item">\n			<a href="javascript:;" data-label_code="{{label_code}}" data-category_code="{{category_code}}" class="card-inner">\n				<img src="{{getImgAbsolutePath img}}">\n				<div class="cover">\n					<div>\n						<h3>{{title}}</h3>\n						<h5>{{subtitle}}</h5>\n					</div>\n				</div>\n			</a>\n		</li>\n	 {{/each}}\n	</ul>\n</div>\n				\n				';
});